version: '3.11'
services:
  postgres:
    restart: always
    image: postgres:15.3-alpine
    container_name: project
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "6432:5432"
    volumes:
      - postgres-data-public:/var/lib/postgresql/data
volumes:
  postgres-data-public: